### ISSUE TITLE
Combat simulation

### ISSUE THREAD

**Issue by Gabb-c** [Gabb-c/pokenode-ts#97]
### Describe the feature you'd like to request

Add a method to simulate a combat between pokémons.

### Describe the solution you'd like

Not applicable

### Describe alternatives you've considered

Not applicable

**Comment by moyzlevi** [comment]
I'm gonna work on this feature

**Comment by moyzlevi** [comment]
I would suggest using this [repository](https://github.com/pvpoke/pvpoke/) as a reference to the battle algorithm. It is really simple, and we could provide some utility to the pokenode-ts' users. 
Full documentation at the end on any battle in the [website](https://pvpoke.com/battle/1500/aipom_shadow/aipom_shadow/11/1-1-3/1-1-3/)
## Description of the Battle Algorithm provided in pvpoke
### Battle Rating 
**Battle Rating** is a metric used to represent each battle's outcome. It is the backbone of PvPoke's rankings. The Battle Rating formula is:

**Battle Rating** = `(500 * (Damage Dealt / Opponent's HP)) + (500 * (HP Remaining / HP))`

### Pokemon Stats
A Pokemon's actual stats are a result of its base stats, IV's, and a CP multiplier (determined by level). The stats shown are a Pokemon's actual stats at the given CP or level. "Overall" is a product of the three stats and gives a general idea for performance, mostly useful for comparing Pokemon of the same or similar species.

### Move Selection
When using the auto select option, the simulator calculates which moves would be optimal in the current matchup. It does this in the steps below:

- Sort Charged Moves by DPE (damage per energy) and select the best move for the "Main" Charged Move. Some Charged Moves deal a lot of damage but take longer to charge, while others charge quickly but deal less damage. DPE helps determine each Pokemon's most efficient move in the matchup.

- Sort remaining Charged Moves by damage per energy squared and select the best move for the "Secondary" Charged Move. Since this weighs moves by energy, fast-charging moves are more likely to be selected than slow ones. This method for selecting a Secondary Charged Move was chosen because the battle algorithm prioritizes fast Charged Moves over the Main Charged Move in certain scenarios, so this helps give Pokemon access to their faster attacks even if they aren't as efficient on paper as other options (e.g. Dragonite with Dragon Claw or Magneton with Discharge).

- Calculate TDO (total damage output) for each Fast Move and select the best option. TDO is simply the product of DPS (how much damage a Pokemon deals per second, on average) and how much time the Pokemon lasts in battle.

### Battle Algorithm
Pokemon GO's Trainer Battles take place in 0.5-second "turns", and the simulator increments through each of those turns while determining the best possible action for both combatants. To determine those actions, the simulator performs the following checks:

1. If the Main Charged Move is available, use it immediately.
2. Use the Secondary Charged Move if:
- It would KO the opponent
- The opponent has a shield 
- The opponent's next action would result in a KO
3. If the opponent is using any Charged Move and shields are available, block it.
4. If none of these are true, use the Fast Move.

This algorithm produces the following behavior:

- Pokemon will use any move available if it would result in a KO.

1. Pokemon will use any move available to deal the most possible damage before they feint.
2. Pokemon will always shield themselves if possible.
3. Pokemon will use their fastest Charged Move to remove an opponent's shields.

This behavior may not always represent human play or strategies, but it's intended to give each Pokemon the best result in the specific battle.

**Comment by moyzlevi** [comment]
I found another possible implementation, it is more simple but it is not and PHP and it is well documented.
https://towardsdatascience.com/gotta-simulate-em-all-pokemon-390553008e2d

**Comment by Gabb-c** [comment]
Hi @moyzlevi, thanks for contributing to pokenode-ts!
I'll check these options and study the Battle Algorithm, so I can help you with this feature.
